name: Test
on: 
    repository_dispatch:
      types: [ provision ]   

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Set env
          run: |
               echo ${{secrets.REMOTE_GIT_REPO}}
        
